import { Project, AuditEvent } from '@/types';

export const projects: Project[] = [
  {
    id: 'TL-001',
    name: 'Delhi–Mumbai Expressway Package IV',
    state: 'Rajasthan',
    district: 'Alwar',
    tehsil: 'Behror',
    village: 'Mandhan',
    pia: 'NHAI',
    landType: 'Agricultural',
    families: 184,
    area: 612.4,
    stage: 'Compensation',
    risk: 'High',
    riskFactor: 'Objections raised under Section 15(1) regarding multi-crop valuation',
    slaDaysLeft: 4,
    compensationDue: 42.8,
    compensationPaid: 31.2,
    possession: 64,
    rr: 48,
    ulpin: 'RJ-ALW-4F8A2',
    updatedAt: '8 min ago',
    parcels: [
      { id: 'P-101', ulpin: 'RJ-ALW-4F8A2-01', surveyNo: '142/1', ownerName: 'Om Prakash Yadav', areaHa: 1.84, status: 'Acquired', coordinates: { x: 18, y: 28 } },
      { id: 'P-102', ulpin: 'RJ-ALW-4F8A2-02', surveyNo: '142/2', ownerName: 'Ramlal Gujjar', areaHa: 2.30, status: 'In Progress', coordinates: { x: 26, y: 35 } },
      { id: 'P-103', ulpin: 'RJ-ALW-4F8A2-03', surveyNo: '143', ownerName: 'Kailash Chand', areaHa: 3.12, status: 'Disputed', coordinates: { x: 32, y: 24 } },
      { id: 'P-104', ulpin: 'RJ-ALW-4F8A2-04', surveyNo: '144/A', ownerName: 'Gram Sabha Land', areaHa: 4.80, status: 'Acquired', coordinates: { x: 22, y: 44 } },
    ]
  },
  {
    id: 'TL-002',
    name: 'Eastern Dedicated Freight Corridor',
    state: 'Uttar Pradesh',
    district: 'Prayagraj',
    tehsil: 'Phulpur',
    village: 'Saidabad',
    pia: 'DFCCIL',
    landType: 'Mixed',
    families: 96,
    area: 304.8,
    stage: 'Possession',
    risk: 'Medium',
    riskFactor: 'Joint measurement survey completed; physical handover in progress',
    slaDaysLeft: 18,
    compensationDue: 26.1,
    compensationPaid: 25.4,
    possession: 82,
    rr: 73,
    ulpin: 'UP-PYG-19AC7',
    updatedAt: '21 min ago',
    parcels: [
      { id: 'P-201', ulpin: 'UP-PYG-19AC7-01', surveyNo: '88/1', ownerName: 'Brijesh Tripathi', areaHa: 1.45, status: 'Acquired', coordinates: { x: 48, y: 55 } },
      { id: 'P-202', ulpin: 'UP-PYG-19AC7-02', surveyNo: '89', ownerName: 'Shyam Sundar', areaHa: 2.10, status: 'Acquired', coordinates: { x: 55, y: 62 } },
      { id: 'P-203', ulpin: 'UP-PYG-19AC7-03', surveyNo: '90/B', ownerName: 'Anil Maurya', areaHa: 0.95, status: 'In Progress', coordinates: { x: 42, y: 68 } },
    ]
  },
  {
    id: 'TL-003',
    name: 'Bengaluru–Chennai Industrial Corridor',
    state: 'Karnataka',
    district: 'Kolar',
    tehsil: 'Malur',
    village: 'Lakkur',
    pia: 'NICDC',
    landType: 'Industrial',
    families: 51,
    area: 188.7,
    stage: 'State Approval',
    risk: 'Low',
    riskFactor: 'State Level Empowered Committee clearance granted smoothly',
    slaDaysLeft: 37,
    compensationDue: 14.6,
    compensationPaid: 0,
    possession: 0,
    rr: 0,
    ulpin: 'KA-KLR-7BC91',
    updatedAt: '1 hr ago',
    parcels: [
      { id: 'P-301', ulpin: 'KA-KLR-7BC91-01', surveyNo: '23', ownerName: 'Venkatesh Murthy', areaHa: 2.65, status: 'Pending Notification', coordinates: { x: 70, y: 32 } },
      { id: 'P-302', ulpin: 'KA-KLR-7BC91-02', surveyNo: '24/1', ownerName: 'KIADB Industrial Reserve', areaHa: 5.40, status: 'Acquired', coordinates: { x: 78, y: 28 } },
    ]
  },
  {
    id: 'TL-004',
    name: 'North–South Freight Corridor Link',
    state: 'Madhya Pradesh',
    district: 'Dhar',
    tehsil: 'Pithampur',
    village: 'Sagore',
    pia: 'RVNL',
    landType: 'Agricultural',
    families: 133,
    area: 476.1,
    stage: 'Award',
    risk: 'Medium',
    riskFactor: 'Preliminary award published; statutory hearing on 22 Sep 2026',
    slaDaysLeft: 12,
    compensationDue: 33.2,
    compensationPaid: 18.9,
    possession: 41,
    rr: 36,
    ulpin: 'MP-DHR-22DE1',
    updatedAt: '2 hrs ago',
    parcels: [
      { id: 'P-401', ulpin: 'MP-DHR-22DE1-01', surveyNo: '312', ownerName: 'Devendra Patel', areaHa: 3.20, status: 'In Progress', coordinates: { x: 50, y: 30 } },
      { id: 'P-402', ulpin: 'MP-DHR-22DE1-02', surveyNo: '313/2', ownerName: 'Rameshwar Solanki', areaHa: 2.80, status: 'Acquired', coordinates: { x: 58, y: 38 } },
    ]
  },
  {
    id: 'TL-005',
    name: 'Mumbai–Nagpur Samruddhi Extension',
    state: 'Maharashtra',
    district: 'Wardha',
    tehsil: 'Seloo',
    village: 'Hingani',
    pia: 'MSRDC',
    landType: 'Mixed',
    families: 74,
    area: 267.3,
    stage: 'Payment',
    risk: 'Low',
    riskFactor: 'Direct purchase consent model adopted with 100% agreement',
    slaDaysLeft: 25,
    compensationDue: 19.7,
    compensationPaid: 18.6,
    possession: 71,
    rr: 68,
    ulpin: 'MH-WRD-5E21A',
    updatedAt: '3 hrs ago',
    parcels: [
      { id: 'P-501', ulpin: 'MH-WRD-5E21A-01', surveyNo: '77', ownerName: 'Sanjay Deshmukh', areaHa: 1.90, status: 'Acquired', coordinates: { x: 62, y: 72 } },
      { id: 'P-502', ulpin: 'MH-WRD-5E21A-02', surveyNo: '78/1', ownerName: 'Gajanan Wankhede', areaHa: 2.15, status: 'Acquired', coordinates: { x: 68, y: 65 } },
    ]
  },
  {
    id: 'TL-006',
    name: 'Coastal Economic Corridor',
    state: 'Odisha',
    district: 'Khordha',
    tehsil: 'Jatni',
    village: 'Khurda Road',
    pia: 'NHAI',
    landType: 'Agricultural',
    families: 211,
    area: 728.9,
    stage: 'Notification',
    risk: 'High',
    riskFactor: 'Section 11(1) preliminary notification approaching 12-month lapse limit',
    slaDaysLeft: 2,
    compensationDue: 51.9,
    compensationPaid: 0,
    possession: 0,
    rr: 0,
    ulpin: 'OD-KHD-81F2B',
    updatedAt: '4 hrs ago',
    parcels: [
      { id: 'P-601', ulpin: 'OD-KHD-81F2B-01', surveyNo: '201', ownerName: 'Pratap Rout', areaHa: 4.10, status: 'Disputed', coordinates: { x: 82, y: 48 } },
      { id: 'P-602', ulpin: 'OD-KHD-81F2B-02', surveyNo: '202/A', ownerName: 'Subhasish Mohanty', areaHa: 3.75, status: 'Pending Notification', coordinates: { x: 88, y: 55 } },
    ]
  }
];

export const auditEvents: AuditEvent[] = [
  {
    id: 'a1',
    projectId: 'TL-001',
    projectName: 'Delhi–Mumbai Expressway Package IV',
    actor: 'Ananya Mehta',
    role: 'District',
    action: 'Section 26 compensation market value assessment submitted for 184 khatas',
    timestamp: '13 Sep 2026 · 17:54',
    status: 'Success'
  },
  {
    id: 'a2',
    projectId: 'TL-001',
    projectName: 'Delhi–Mumbai Expressway Package IV',
    actor: 'Ravi Kumar',
    role: 'Field Officer',
    action: 'Biometric validation completed for 184 project-affected families',
    timestamp: '13 Sep 2026 · 17:41',
    status: 'Success'
  },
  {
    id: 'a3',
    projectId: 'TL-002',
    projectName: 'Eastern Dedicated Freight Corridor',
    actor: 'State Land Cell',
    role: 'State',
    action: 'Possession certificate under Section 38 formally uploaded and sealed',
    timestamp: '13 Sep 2026 · 17:22',
    status: 'Success'
  },
  {
    id: 'a4',
    projectId: 'TL-006',
    projectName: 'Coastal Economic Corridor',
    actor: 'TerraLink AI Engine',
    role: 'Ministry',
    action: 'Critical delay risk flagged: SLA expiration in 48 hours for Notification stage',
    timestamp: '13 Sep 2026 · 16:58',
    status: 'Warning'
  },
  {
    id: 'a5',
    projectId: 'TL-005',
    projectName: 'Mumbai–Nagpur Samruddhi Extension',
    actor: 'MSRDC Land Desk',
    role: 'PIA',
    action: 'Direct PFMS disbursement authorization initiated for 68 khatedars',
    timestamp: '13 Sep 2026 · 15:30',
    status: 'Success'
  },
  {
    id: 'a6',
    projectId: 'TL-004',
    projectName: 'North–South Freight Corridor Link',
    actor: 'Pithampur Competent Authority',
    role: 'District',
    action: 'Public notice issued for determination of award hearing under Section 23',
    timestamp: '13 Sep 2026 · 14:15',
    status: 'Pending'
  }
];
